services:
  - type: web
    name: ganeth-portfolio-frontend
    runtime: node
    region: ohio
    plan: free
    buildCommand: |
      npm install
      npm install serve
      npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: PORT
        value: 10000
    healthCheckPath: /